foods = [
    {name: "Apple", image:"https://images.unsplash.com/photo-1505872342847-6dbb5e76cd31?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"},
    {name: "Apricot", image:"https://images.unsplash.com/photo-1552417569-262c0e72f374?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=966&q=80"},
    {name: "Asparagus", image:"https://images.unsplash.com/photo-1555919808-a3635c28ac77?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80"},
    {name: "Aubergine", image:"https://images.pexels.com/photos/321551/pexels-photo-321551.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"},
    {name: "Banana", image:"https://images.pexels.com/photos/365810/pexels-photo-365810.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"},
    {name: "Basil", image:"https://images.unsplash.com/photo-1536777206078-5e694d16c678?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"},
    {name: "Beef", image:"https://images.unsplash.com/photo-1448907503123-67254d59ca4f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1049&q=80"},
    {name: "Beetroot", image:"https://images.unsplash.com/photo-1533231040102-5ec7a63e6d0a?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80"},
    {name: "Blackberry", image:"https://images.unsplash.com/photo-1474480109237-15a7ca8f0685?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1053&q=80"},
    {name: "Blackcurrants", image:"https://images.pexels.com/photos/937659/pexels-photo-937659.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"},
    {name: "Bramley apple", image:"https://images.unsplash.com/photo-1480525560316-45061b85b605?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1053&q=80"},
    {name: "Broad bean", image:"https://gbc.blob.core.windows.net/media/img26455.jpg"},
    {name: "Broccoli", image:"https://images.unsplash.com/photo-1550409174-a8ea3586299c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1049&q=80"},
    {name: "Brussels sprouts", image:"https://images.pexels.com/photos/41171/brussels-sprouts-sprouts-cabbage-grocery-41171.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"},
    {name: "Cabbage", image:"https://images.unsplash.com/photo-1508302730834-a3786a6c951d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"},
    {name: "Carrot", image:"https://images.unsplash.com/photo-1447175008436-054170c2e979?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1161&q=80"},
    {name: "Cauliflower", image:"https://images.unsplash.com/photo-1510627498534-cf7e9002facc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80"},
    {name: "Cavolo nero", image:"https://gbc-cdn-public-media.azureedge.net/img74757.1426x713.jpg"},
    {name: "Celeriac", image:"https://img.crocdn.co.uk/images/products2/pl/20/00/01/47/pl2000014706.jpg?width=940&height=940"},
    {name: "Celery", image:"https://cdn1.medicalnewstoday.com/content/images/articles/270/270678/celery.jpg"},
    {name: "Cherry", image:"https://images.unsplash.com/photo-1520236060906-9c5ed525b025?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"},
    {name: "Chervil", image:"https://cdn11.bigcommerce.com/s-2ba96/images/stencil/1200x1800/products/748/1254/ChervilPlantFreak__96938.1458334645.jpg?c=2"},
    {name: "Chestnut", image:"https://cdn.pixabay.com/photo/2016/09/28/17/48/chestnut-1701045_960_720.jpg"},
    {name: "Chicken", image:"https://www.simplyrecipes.com/wp-content/uploads/2015/09/roasted-chicken-apricot-glaze-horiz-a-1500.jpg"},
    {name: "Chicory", image:"https://www.bbcgoodfood.com/sites/default/files/glossary/chicory.jpg"},
    {name: "Clementine", image:"https://images.unsplash.com/photo-1459663296021-50769c04b149?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"},
    {name: "Cod", image:"https://img.taste.com.au/iP1FrDcO/taste/2016/11/oven-roasted-cod-with-mustard-crust-11330-1.jpeg"},
    {name: "Courgette", image:"https://images.pexels.com/photos/128420/pexels-photo-128420.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"},
    {name: "Courgette flower", image:"http://tuscantraveler.com/wordpress/wp-content/uploads/2015/06/zucchiniflowers1.jpg"},
    {name: "Crab", image:"https://images.unsplash.com/photo-1547571233-02e0e8dc6a76?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"},
    {name: "Crab apple", image:"https://mrsportlyskitchen.files.wordpress.com/2016/08/basket-copy.jpg"},
    {name: "Cranberry", image:"https://images.pexels.com/photos/139917/pexels-photo-139917.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"},
    {name: "Damson", image: "https://images.pexels.com/photos/209378/pexels-photo-209378.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"},
    {name: "Date", image:"https://images.unsplash.com/photo-1537201872643-ff006e1f016f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"},
    {name: "Duck", image:"https://gbc-cdn-public-media.azureedge.net/img24404.1426x713.jpg"},
    {name: "Elderberries", image:"https://www.sciencedaily.com/images/2019/04/190423133644_1_540x360.jpg"},
    {name: "Fennel", image:"https://gbc-cdn-public-media.azureedge.net/img26518.640x360.jpg"},
    {name: "Fig", image:"https://images.unsplash.com/photo-1557837201-38eaf28b3031?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60"},
    {name: "Garlic", image:"https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"},
    {name: "Globe artichoke", image:"https://images.unsplash.com/photo-1518735869015-566a18eae4be?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1069&q=80"},
    {name: "Goose", image:"https://www.raymondblanc.com/wp-content/uploads/2018/11/Raymond_Blanc_Web_Winter18-165-e1544701589607.jpg"},
    {name: "Gooseberry", image:"https://www.burmaspice.com/wp-content/uploads/2017/06/Cherry-Plum-for-Sale-480x320.jpg"},
    {name: "Grapefruit", image:"https://images.unsplash.com/photo-1512580344356-fd2f966fbeae?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1534&q=80"},
    {name: "Grouse", image:"https://gbc.blob.core.windows.net/media/img43204.jpg"},
    {name: "Guinea fowl", image:"https://images.eatsmarter.com/sites/default/files/styles/920x690/public/guinea-fowl-with-pears-and-dates-617766.jpg"},
    {name: "Halibut", image:"https://assets.epicurious.com/photos/54dcdff74f77a310045d2bee/master/pass/51263770_pan-roasted-halibut_1x1.jpg"},
    {name: "Jerusalem artichoke", image:"https://www.sbs.com.au/food/sites/sbs.com.au.food/files/181_roasted-chicken-jerusalem-artichoke-and-lemon.jpg"},
    {name: "Kale", image:"https://images.unsplash.com/photo-1522193582792-c66cf1cddd16?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80"},
    {name: "Kipper", image:"https://www.thefishsociety.co.uk/media/image/49/f2/ae/Boned-kippers-new-website_600x600.jpg"},
    {name: "Kohlrabi", image:"https://www.thespruceeats.com/thmb/24YL-LkewT8SYSRhF9ITYs_tfu4=/2079x1442/filters:no_upscale()/GettyImages-492528037-5a8f20f63037130037df81b5.jpg"},
    {name: "Lamb", image:"https://food-images.files.bbci.co.uk/food/recipes/roast_leg_of_lamb_with_32711_16x9.jpg"},
    {name: "Lamb's lettuce", image:"https://www.chilternseeds.co.uk/images/products/zoom/img_8588_5531.jpg"},
    {name: "Leek", image:"https://myhealthygram.com/wp-content/uploads/2018/01/leek.jpg"},
    {name: "Lemon", image:"https://images.unsplash.com/photo-1508902708314-25ca18334a11?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"},
    {name: "Lettuce", image:"https://images.unsplash.com/photo-1543056295-d585ba290712?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=967&q=80"},
    {name: "Loganberry", image:"https://www.ashridgetrees.co.uk/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/l/o/loganberries-1.jpg"},
    {name: "Mackerel", image:"https://realfood.tesco.com/media/images/mackerel-with-citrus-chickpeas-LH-aaca94c5-07c8-4664-9d5d-50aab846f8f5-0-1400x919.jpg"},
    {name: "Mangetout", image:"https://veg-inabox.com/wp-content/uploads/2018/01/mange-tout-2.jpg"},
    {name: "Marrow", image:"https://www.simplyseed.co.uk/user/products/Marrow%20Bush%20Baby.jpg"},
    {name: "Mint", image:"https://images.unsplash.com/photo-1509727841791-40d09ad9b7fc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"},
    {name: "Mussels", image:"https://images.unsplash.com/photo-1466553556096-7e2c49388e34?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1489&q=80"},
    {name: "Nectarine", image:"http://rainbow-foods.org/wp-content/uploads/2017/06/nectarines.jpg"},
    {name: "New potatoes", image:"https://pcdn.columbian.com/wp-content/uploads/2018/06/0622_WKD_Market-Fresh-new-potatoes.jpg"},
    {name: "Onion", image:"https://images.unsplash.com/photo-1508747703725-719777637510?ixlib=rb-1.2.1&auto=format&fit=crop&w=967&q=80"},
    {name: "Orange", image:"https://images.unsplash.com/photo-1476523165843-79f78d654922?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1189&q=80"},
    {name: "Oyster", image:"https://images.unsplash.com/photo-1515503249716-e0175c9d8fab?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=967&q=80"},
    {name: "Pak choi", image:"https://sakata.co.za/wp-content/uploads/2015/07/JOI-CHOI.jpg"},
    {name: "Parsnip", image:"https://suttons.s3.amazonaws.com/p/VEPAR35097_3.jpg"},
    {name: "Peach", image:"https://images.unsplash.com/photo-1532704868953-d85f24176d73?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"},
    {name: "Pear", image:"https://images.unsplash.com/photo-1514756331096-242fdeb70d4a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"},
    {name: "Peas", image:"https://images.pexels.com/photos/255469/pexels-photo-255469.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"},
    {name: "Pepper", image:"https://images.pexels.com/photos/128536/pexels-photo-128536.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"},
    {name: "Plum", image:"https://images.unsplash.com/photo-1560287820-f71eda3d75c9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=700&q=80"},
    {name: "Pomegranate", image:"https://images.unsplash.com/photo-1541344999736-83eca272f6fc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80"},
    {name: "Pork", image:"https://images.unsplash.com/photo-1523986490752-c28064f26be3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80"},
    {name: "Potato", image:"https://images.pexels.com/photos/162763/delicious-garnish-potatoes-fried-162763.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"},
    {name: "Pumpkin", image:"https://images.unsplash.com/photo-1507637246364-d8fce4a9850a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"},
    {name: "Purple sprouting broccoli", image:"https://gardeners.s3.amazonaws.com/p/VEBRO33781_3.jpg"},
    {name: "Quince", image:"https://s7148.pcdn.co/wp-content/uploads/3CAB4C78-C744-49EA-8AD3-3151C799CBC9.jpeg"},
    {name: "Radicchio", image:"https://images-na.ssl-images-amazon.com/images/I/81U4yMiIRpL._SX425_.jpg"},
    {name: "Radish", image:"https://images.unsplash.com/photo-1530196116728-b7d64739b557?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"},
    {name: "Raspberry", image:"https://images.unsplash.com/photo-1514756062153-4d9b55947090?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80"},
    {name: "Redcurrant", image:"https://images.pexels.com/photos/2479247/pexels-photo-2479247.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"},
    {name: "Rhubarb", image:"https://images.unsplash.com/photo-1507484467459-0c01be16726e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80"},
    {name: "Runner bean", image:"https://www.bbcgoodfood.com/sites/default/files/glossary/runner-bean-glossary-image.jpg"},
    {name: "Salmon", image:"https://images.unsplash.com/photo-1499125562588-29fb8a56b5d5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1189&q=80"},
    {name: "Salsify", image:"https://www.heligan.com/images/uploads/_DSC7797.jpg"},
    {name: "Samphire", image:"https://www.runnymedehotel.com/wp-content/uploads/2017/07/Samphire--1200x795.jpg"},
    {name: "Sorrel", image:"https://q7i2y6d5.stackpathcdn.com/wp-content/uploads/2011/07/sorrel-1-400x267.jpg"},
    {name: "Spinach", image:"https://images.unsplash.com/photo-1515363578674-99f41329ab4c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1494&q=80"},
    {name: "Spring greens", image:"https://www.abelandcole.co.uk/media/6377_15062_m.jpg"},
    {name: "Spring onion", image:"https://images.pexels.com/photos/315696/pexels-photo-315696.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"},
    {name: "Strawberry", image:"https://images.unsplash.com/photo-1519180392711-496e450edf6a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"},
    {name: "Swede", image:"https://gardeners.s3.amazonaws.com/p/VESWE24018_3.jpg"},
    {name: "Sweet potato", image:"https://cdn-images-1.medium.com/max/923/1*Ap5ITw25jbWmzDR64Tm_kw.jpeg"},
    {name: "Sweetcorn", image:"https://images.unsplash.com/photo-1440668737548-aa725b277c81?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"},
    {name: "Swiss chard", image:"https://edge.bonnieplants.com/www/uploads/20180920003711/swiss-chard1.jpg"},
    {name: "Tayberry", image:"https://img.auctiva.com/imgdata/3/8/6/5/6/4/webimg/778857515_o.jpg"},
    {name: "Tomato", image:"https://images.unsplash.com/photo-1513099809760-bbe4a4b21b9b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"},
    {name: "Tuna", image:"https://www.seriouseats.com/recipes/images/2016/08/20160827-sous-vide-tuna-41-1500x1125.jpg"},
    {name: "Turkey", image:"https://cookthestory.com/wp-content/uploads/2018/10/Perfectly-Roast-Turkey-1392x780.jpg"},
    {name: "Turnip", image:"https://www.daringgourmet.com/wp-content/uploads/2016/08/Pickled-Turnips-6.jpg"},
    {name: "Venison", image:"https://www.foodrepublic.com/wp-content/uploads/2016/04/rackofvenison.jpg"},
    {name: "Watercress", image:"https://assets.bonappetit.com/photos/589cd21605f7121026acb5d3/16:9/w_1200,c_limit/watercress-salad-with-mustard-vinaigrette.jpg"},
    {name: "Watermelon", image:"https://images.pexels.com/photos/1068534/pexels-photo-1068534.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"},
    {name: "Whiting", image:"https://www.goodfood.com.au/content/dam/images/g/s/z/v/5/h/image.related.wideLandscape.940x529.gszu0i.png/1481673093856.jpg"},
]

months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]

seasons = [
    {
        month: "January",
        foods: [
            "Apple",
            "Beef",
            "Beetroot",
            "Bramley apple",
            "Brussels sprouts",
            "Cabbage",
            "Cauliflower",
            "Celeriac",
            "Celery",
            "Chestnut",
            "Chicken",
            "Chicory",
            "Cod",
            "Date",
            "Goose",
            "Jerusalem artichoke",
            "Kale",
            "Lamb",
            "Leek",
            "Mussels",
            "Onion",
            "Oyster",
            "Pak choi",
            "Parsnip",
            "Pear",
            "Pork",
            "Purple sprouting broccoli",
            "Radicchio",
            "Rhubarb",
            "Salsify",
            "Spring onion",
            "Swede",
            "Sweet potato",
            "Turnip",
            "Venison",
            "Whiting"
        ]
    },
    {
        month: "February",
        foods: [
            "Apple",
            "Beef",
            "Bramley apple",
            "Brussels sprouts",
            "Cabbage",
            "Cauliflower",
            "Celeriac",
            "Celery",
            "Chicken",
            "Chicory",
            "Cod",
            "Jerusalem artichoke",
            "Kale",
            "Lamb",
            "Leek",
            "Mussels",
            "Onion",
            "Oyster",
            "Pak choi",
            "Parsnip",
            "Pork",
            "Purple sprouting broccoli",
            "Radicchio",
            "Rhubarb",
            "Spring onion",
            "Swede",
            "Sweet potato",
            "Turnip",
            "Venison",
            "Whiting"        
        ]
    },
    {
        month: "March",
        foods: [
            "Beef",
            "Bramley apple",
            "Brussels sprouts",
            "Cabbage",
            "Cauliflower",
            "Celeriac",
            "Chicken",
            "Chicory",
            "Cod",
            "Halibut",
            "Jerusalem artichoke",
            "Lamb",
            "Leek",
            "Mussels",
            "Onion",
            "Oyster",
            "Pak choi",
            "Parsnip",
            "Pork",
            "Potato",
            "Purple sprouting broccoli",
            "Radicchio",
            "Rhubarb",
            "Salmon",
            "Sorrel",
            "Spinach",
            "Spring greens",
            "Spring onion",
            "Sweet potato",
            "Turnip",
            "Watercress"       
        ]
    },
    {
        month: "April",
        foods: [
            "Beef",
            "Cabbage",
            "Cauliflower",
            "Celeriac",
            "Chicken",
            "Cod",
            "Crab",
            "Halibut",
            "Lamb",
            "Lettuce",
            "New potatoes",
            "Onion",
            "Oyster",
            "Pak choi",
            "Peas",
            "Pork",
            "Potato",
            "Purple sprouting broccoli",
            "Radicchio",
            "Radish",
            "Rhubarb",
            "Salmon",
            "Sorrel",
            "Spinach",
            "Spring greens",
            "Spring onion",
            "Turnip",
            "Watercress"        
        ]
    },
    {
        month: "May",
        foods: [
            "Asparagus",
            "Beef",
            "Blackcurrants",
            "Cabbage",
            "Carrot",
            "Chervil",
            "Chicken",
            "Crab",
            "Globe artichoke",
            "Gooseberry",
            "Halibut",
            "Kipper",
            "Lamb",
            "Lamb's lettuce",
            "Lettuce",
            "Mackerel",
            "Mint",
            "New potatoes",
            "Onion",
            "Pak choi",
            "Peas",
            "Pork",
            "Potato",
            "Radicchio",
            "Radish",
            "Rhubarb",
            "Salmon",
            "Sorrel",
            "Spinach",
            "Spring greens",
            "Spring onion",
            "Strawberry",
            "Tomato",
            "Tuna",
            "Watercress"        
        ]
    },
    {
        month: "June",
        foods: [
            "Asparagus",
            "Aubergine",
            "Basil",
            "Beef",
            "Blackcurrants",
            "Broad bean",
            "Cabbage",
            "Carrot",
            "Cavolo nero",
            "Cherry",
            "Chervil",
            "Chicken",
            "Courgette",
            "Courgette flower",
            "Crab",
            "Fennel",
            "Garlic",
            "Globe artichoke",
            "Gooseberry",
            "Halibut",
            "Kipper",
            "Lamb",
            "Lamb's lettuce",
            "Lettuce",
            "Mackerel",
            "Mangetout",
            "Mint",
            "New potatoes",
            "Onion",
            "Pak choi",
            "Peas",
            "Pepper",
            "Pork",
            "Potato",
            "Radicchio",
            "Radish",
            "Raspberry",
            "Redcurrant",
            "Rhubarb",
            "Runner bean",
            "Salmon",
            "Sorrel",
            "Spinach",
            "Spring greens",
            "Spring onion",
            "Strawberry",
            "Tomato",
            "Tuna",
            "Watercress",
            "Whiting"        
        ]
    },
    {
        month: "July",
        foods: [
            "Asparagus",
            "Aubergine",
            "Basil",
            "Beef",
            "Beetroot",
            "Blackberry",
            "Blackcurrants",
            "Broad bean",
            "Broccoli",
            "Cabbage",
            "Carrot",
            "Cavolo nero",
            "Celery",
            "Cherry",
            "Chervil",
            "Chicken",
            "Courgette",
            "Courgette flower",
            "Crab",
            "Fennel",
            "Garlic",
            "Globe artichoke",
            "Gooseberry",
            "Halibut",
            "Kipper",
            "Kohlrabi",
            "Lamb",
            "Lamb's lettuce",
            "Lettuce",
            "Mackerel",
            "Mangetout",
            "Marrow",
            "Mint",
            "New potatoes",
            "Onion",
            "Pak choi",
            "Peas",
            "Pepper",
            "Pork",
            "Potato",
            "Radicchio",
            "Radish",
            "Raspberry",
            "Redcurrant",
            "Runner bean",
            "Salmon",
            "Samphire",
            "Sorrel",
            "Spinach",
            "Spring onion",
            "Strawberry",
            "Swiss chard",
            "Tayberry",
            "Tomato",
            "Tuna",
            "Watercress",
            "Whiting"        
        ]
    },
    {
        month: "August",
        foods: [
            "Aubergine",
            "Basil",
            "Beef",
            "Beetroot",
            "Blackberry",
            "Broad bean",
            "Broccoli",
            "Cabbage",
            "Carrot",
            "Cavolo nero",
            "Celery",
            "Chervil",
            "Chicken",
            "Courgette",
            "Courgette flower",
            "Crab",
            "Crab apple",
            "Damson",
            "Elderberries",
            "Fennel",
            "Garlic",
            "Globe artichoke",
            "Goose",
            "Gooseberry",
            "Grouse",
            "Guinea fowl",
            "Halibut",
            "Kipper",
            "Kohlrabi",
            "Lamb",
            "Lamb's lettuce",
            "Lettuce",
            "Loganberry",
            "Mackerel",
            "Mangetout",
            "Marrow",
            "Mint",
            "Onion",
            "Pak choi",
            "Peach",
            "Peas",
            "Pepper",
            "Plum",
            "Pork",
            "Radicchio",
            "Radish",
            "Raspberry",
            "Redcurrant",
            "Runner bean",
            "Salmon",
            "Samphire",
            "Sorrel",
            "Spinach",
            "Spring onion",
            "Strawberry",
            "Sweetcorn",
            "Swiss chard",
            "Tayberry",
            "Tomato",
            "Tuna",
            "Watercress"        
        ]
    },
    {
        month: "September",
        foods: [
            "Apple",
            "Aubergine",
            "Beef",
            "Beetroot",
            "Blackberry",
            "Broad bean",
            "Broccoli",
            "Cabbage",
            "Carrot",
            "Cavolo nero",
            "Celeriac",
            "Celery",
            "Chervil",
            "Chestnut",
            "Chicken",
            "Courgette",
            "Crab",
            "Damson",
            "Elderberries",
            "Fennel",
            "Garlic",
            "Globe artichoke",
            "Goose",
            "Gooseberry",
            "Grouse",
            "Guinea fowl",
            "Halibut",
            "Kale",
            "Kipper",
            "Kohlrabi",
            "Lamb",
            "Lamb's lettuce",
            "Leek",
            "Lettuce",
            "Loganberry",
            "Mackerel",
            "Marrow",
            "Mint",
            "Onion",
            "Pak choi",
            "Parsnip",
            "Pear",
            "Peas",
            "Pepper",
            "Plum",
            "Pork",
            "Pumpkin",
            "Quince",
            "Radicchio",
            "Radish",
            "Raspberry",
            "Redcurrant",
            "Runner bean",
            "Salmon",
            "Salsify",
            "Sorrel",
            "Spinach",
            "Spring onion",
            "Sweetcorn"        
        ]
    },
    {
        month: "October",
        foods: [
            "Apple",
            "Beef",
            "Beetroot",
            "Blackberry",
            "Broccoli",
            "Brussels sprouts",
            "Cabbage",
            "Cavolo nero",
            "Celeriac",
            "Celery",
            "Chestnut",
            "Chicken",
            "Crab",
            "Cranberry",
            "Duck",
            "Elderberries",
            "Fig",
            "Garlic",
            "Globe artichoke",
            "Goose",
            "Grouse",
            "Guinea fowl",
            "Jerusalem artichoke",
            "Kale",
            "Kohlrabi",
            "Lamb",
            "Lamb's lettuce",
            "Leek",
            "Lettuce",
            "Mackerel",
            "Mussels",
            "Onion",
            "Oyster",
            "Pak choi",
            "Parsnip",
            "Pear",
            "Peas",
            "Plum",
            "Pork",
            "Pumpkin",
            "Quince",
            "Radicchio",
            "Radish",
            "Runner bean",
            "Salsify",
            "Spring onion",
            "Swede",
            "Sweet potato",
            "Swiss chard",
            "Turnip",
            "Venison",
            "Whiting"        
        ]
    },
    {
        month: "November",
        foods: [
            "Apple",
            "Beef",
            "Beetroot",
            "Bramley apple",
            "Brussels sprouts",
            "Cabbage",
            "Celeriac",
            "Celery",
            "Chestnut",
            "Chicken",
            "Crab",
            "Cranberry",
            "Date",
            "Duck",
            "Globe artichoke",
            "Goose",
            "Grouse",
            "Guinea fowl",
            "Jerusalem artichoke",
            "Kale",
            "Kohlrabi",
            "Lamb",
            "Lamb's lettuce",
            "Leek",
            "Lettuce",
            "Mussels",
            "Onion",
            "Oyster",
            "Pak choi",
            "Parsnip",
            "Pear",
            "Peas",
            "Pork",
            "Pumpkin",
            "Quince",
            "Radicchio",
            "Runner bean",
            "Salsify",
            "Spring onion",
            "Swede",
            "Sweet potato",
            "Swiss chard",
            "Turnip",
            "Venison",
            "Whiting"        
        ]
    },
    {
        month: "December",
        foods: [
            "Apple",
            "Beef",
            "Beetroot",
            "Bramley apple",
            "Brussels sprouts",
            "Cabbage",
            "Cauliflower",
            "Celeriac",
            "Celery",
            "Chestnut",
            "Chicken",
            "Cranberry",
            "Duck",
            "Goose",
            "Grapefruit",
            "Grouse",
            "Jerusalem artichoke",
            "Kale",
            "Lamb",
            "Leek",
            "Lettuce",
            "Mussels",
            "Onion",
            "Oyster",
            "Pak choi",
            "Parsnip",
            "Pear",
            "Pork",
            "Pumpkin",
            "Quince",
            "Radicchio",
            "Salsify",
            "Spring onion",
            "Swede",
            "Sweet potato",
            "Turkey",
            "Turnip",
            "Venison"        
        ]
    }
]

# foods.each do |food|
#     food = Food.create(name: food[:name], image: food[:image])
# end

# months.each do |month|
#     Month.create(name: month)
# end

# seasons.each do |season|
#     this_month = Month.all.find{ |month| month[:name] == season[:month] }
#     m_id = this_month[:id]
#     season[:foods].each do |food|
#         this_food = Food.all.find{ |f| f[:name] == food }
#         f_id = this_food[:id]
#         FoodMonth.create(food_id: f_id, month_id: m_id)
#     end
# end

# harriet = User.create(name: "Harriet", password: "harriet")
# dunia = User.create(name: "Dunia", password: "dunia")
# xabi = User.create(name: "Xabi", password: "xabi")

# require 'json'
# require 'rest-client'

# Food.all.each do |food|
#     url = "https://spoonacular-recipe-food-nutrition-v1.p.rapidapi.com/recipes/findByIngredients?number=10&ignorePantry=true&ingredients=#{food.name}"
#     response = RestClient.get(url, headers ={"X-RapidAPI-Host": 'spoonacular-recipe-food-nutrition-v1.p.rapidapi.com', "X-RapidAPI-Key": '72161c23c9mshff16fb4cfa94eb4p14ebaejsn587b8503e8d3'})
#     hash = JSON.parse(response)
#     result = []
#     test = hash.each do |recipe| 
#         element = {title: recipe["title"], missedIngredients: recipe["missedIngredients"], usedIngredients: recipe["usedIngredients"]}
#         result << element
#     end
#     result.each do |recipe|
#         recipe = Recipe.create(title: recipe[:title])
#         RecipeIngredient.create(food_id: food.id, recipe_id: recipe.id)
#     end
# end
